//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaintForest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EstadosDeLaFactura
    {
        public EstadosDeLaFactura()
        {
            this.Facturas = new HashSet<Facturas>();
        }
    
        public int Id { get; set; }
        public string EstadoFactura { get; set; }
    
        public virtual ICollection<Facturas> Facturas { get; set; }
    }
}
