//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaintForest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Habitaciones
    {
        public Habitaciones()
        {
            this.Imagenes = new HashSet<Imagenes>();
            this.Reservas = new HashSet<Reservas>();
        }
    
        public int Id { get; set; }
        public string NombreHabitacion { get; set; }
        public string Dirrecion { get; set; }
        public int TipoHabitacion { get; set; }
        public int EstadoActivo { get; set; }
        public int Disponilidad { get; set; }
        public int EstadoLimpieza { get; set; }
        public string Descripcion { get; set; }
        public decimal Precio { get; set; }
    
        public virtual Disponibilidad Disponibilidad { get; set; }
        public virtual EstadoActivo EstadoActivo1 { get; set; }
        public virtual EstadoLimpieza EstadoLimpieza1 { get; set; }
        public virtual TipoHabitaciones TipoHabitaciones { get; set; }
        public virtual ICollection<Imagenes> Imagenes { get; set; }
        public virtual ICollection<Reservas> Reservas { get; set; }
    }
}
