//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaintForest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Imagenes
    {
        public Nullable<int> IdArticulo { get; set; }
        public string RutaImagen { get; set; }
        public Nullable<int> IdHabitacion { get; set; }
        public int Id { get; set; }
    
        public virtual Habitaciones Habitaciones { get; set; }
        public virtual Productos Productos { get; set; }
    }
}
