//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaintForest.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EntidadesSaintForest : DbContext
    {
        public EntidadesSaintForest()
            : base("name=EntidadesSaintForest")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<DetallePedido> DetallePedido { get; set; }
        public DbSet<Disponibilidad> Disponibilidad { get; set; }
        public DbSet<EstadoActivo> EstadoActivo { get; set; }
        public DbSet<EstadoDeLaReserva> EstadoDeLaReserva { get; set; }
        public DbSet<EstadoLimpieza> EstadoLimpieza { get; set; }
        public DbSet<EstadosDeLaFactura> EstadosDeLaFactura { get; set; }
        public DbSet<EstadosDelPedido> EstadosDelPedido { get; set; }
        public DbSet<Facturas> Facturas { get; set; }
        public DbSet<Habitaciones> Habitaciones { get; set; }
        public DbSet<Imagenes> Imagenes { get; set; }
        public DbSet<Pedidos> Pedidos { get; set; }
        public DbSet<Productos> Productos { get; set; }
        public DbSet<Reservas> Reservas { get; set; }
        public DbSet<Roles> Roles { get; set; }
        public DbSet<SiNo> SiNo { get; set; }
        public DbSet<TipoHabitaciones> TipoHabitaciones { get; set; }
        public DbSet<Usuarios> Usuarios { get; set; }
    }
}
