//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaintForest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Productos
    {
        public Productos()
        {
            this.DetallePedido = new HashSet<DetallePedido>();
            this.Imagenes = new HashSet<Imagenes>();
        }
    
        public int Id { get; set; }
        public string Nombre { get; set; }
        public string Presentacion { get; set; }
        public Nullable<decimal> Iva { get; set; }
        public Nullable<decimal> Ico { get; set; }
        public decimal Valor { get; set; }
        public int Estado { get; set; }
    
        public virtual ICollection<DetallePedido> DetallePedido { get; set; }
        public virtual EstadoActivo EstadoActivo { get; set; }
        public virtual ICollection<Imagenes> Imagenes { get; set; }
    }
}
