//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaintForest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuarios
    {
        public Usuarios()
        {
            this.Facturas = new HashSet<Facturas>();
            this.Pedidos = new HashSet<Pedidos>();
            this.Reservas = new HashSet<Reservas>();
        }
    
        public int Id { get; set; }
        public string Nombres { get; set; }
        public string Apellidos { get; set; }
        public int IdRol { get; set; }
        public string Email { get; set; }
        public string Contraseña { get; set; }
        public Nullable<int> Estado { get; set; }
    
        public virtual EstadoActivo EstadoActivo { get; set; }
        public virtual ICollection<Facturas> Facturas { get; set; }
        public virtual ICollection<Pedidos> Pedidos { get; set; }
        public virtual ICollection<Reservas> Reservas { get; set; }
        public virtual Roles Roles { get; set; }
    }
}
